# Generated by Django 5.1.2 on 2025-02-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyFeudGameProperCenter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('questions', models.TextField()),
                ('answer', models.TextField()),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyFeudGameProperLeft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_2_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FamilyFeudGameProperMaam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('questions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FamilyFeudGameProperRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1_score', models.IntegerField()),
            ],
        ),
    ]
