# Generated by Django 5.1.2 on 2025-02-20 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_feudquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feudquestion',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='feudquestion',
            name='points',
        ),
        migrations.CreateModel(
            name='FeudAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='myapp.feudquestion')),
            ],
        ),
    ]
