# Generated by Django 5.1.2 on 2025-02-21 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_familyfeudgamepropercenter_and_more'),
    ]

    operations = [
    ]
