# Generated by Django 5.1.2 on 2025-02-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_create_initial_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='feudquestion',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
