# Generated by Django 5.1.6 on 2025-02-23 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_feudquestion_feudanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='FeudQuestion',
            new_name='FastMoneyQuestion',
        ),
        migrations.RenameModel(
            old_name='FeudAnswer',
            new_name='Answer',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='myapp.question'),
        ),
    ]
