# Generated by Django 5.1.6 on 2025-02-23 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_question_rename_feudquestion_fastmoneyquestion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='RoundGameAnswer',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='RoundGameQuestion',
        ),
    ]
